[2024-11-06T09:05:26.997+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-06T09:05:27.042+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_etl_dag.extract_data manual__2024-11-06T09:05:23.848721+00:00 [queued]>
[2024-11-06T09:05:27.083+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_etl_dag.extract_data manual__2024-11-06T09:05:23.848721+00:00 [queued]>
[2024-11-06T09:05:27.084+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 4
[2024-11-06T09:05:27.138+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): extract_data> on 2024-11-06 09:05:23.848721+00:00
[2024-11-06T09:05:27.158+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'stock_etl_dag', 'extract_data', 'manual__2024-11-06T09:05:23.848721+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/stock_dag.py', '--cfg-path', '/tmp/tmp26yp5v3u']
[2024-11-06T09:05:27.162+0000] {standard_task_runner.py:105} INFO - Job 35: Subtask extract_data
[2024-11-06T09:05:27.166+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=936) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-06T09:05:27.171+0000] {standard_task_runner.py:72} INFO - Started process 979 to run task
[2024-11-06T09:05:27.371+0000] {task_command.py:467} INFO - Running <TaskInstance: stock_etl_dag.extract_data manual__2024-11-06T09:05:23.848721+00:00 [running]> on host 451d6f396410
[2024-11-06T09:05:27.693+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='stock_etl_dag' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-06T09:05:23.848721+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-06T09:05:23.848721+00:00'
[2024-11-06T09:05:27.699+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-06T09:05:27.699+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-06T09:05:27.700+0000] {logging_mixin.py:190} INFO - Current task name:extract_data state:running start_date:2024-11-06 09:05:27.044978+00:00
[2024-11-06T09:05:27.700+0000] {logging_mixin.py:190} INFO - Dag name:stock_etl_dag and current dag run status:running
[2024-11-06T09:05:27.701+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-06T09:05:30.214+0000] {logging_mixin.py:190} WARNING - [*********************100%***********************]  1 of 1 completed
[2024-11-06T09:05:30.249+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/stock_dag.py", line 16, in extract_stock_data
    data.to_csv('/Users/sushrinadhakal/airflow_stock/data/raw_data.csv')
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 3902, in to_csv
    return DataFrameRenderer(formatter).to_csv(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/format.py", line 1152, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/csvs.py", line 247, in save
    with get_handle(
         ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 739, in get_handle
    check_parent_directory(str(handle))
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 604, in check_parent_directory
    raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
OSError: Cannot save file into a non-existent directory: '/Users/sushrinadhakal/***_stock/data'
[2024-11-06T09:05:30.300+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-06T09:05:30.301+0000] {logging_mixin.py:190} INFO - Task start:2024-11-06 09:05:27.044978+00:00 end:2024-11-06 09:05:30.298878+00:00 duration:3.2539
[2024-11-06T09:05:30.302+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): extract_data> dag:<DAG: stock_etl_dag> dagrun:<DagRun stock_etl_dag @ 2024-11-06 09:05:23.848721+00:00: manual__2024-11-06T09:05:23.848721+00:00, state:running, queued_at: 2024-11-06 09:05:23.974752+00:00. externally triggered: True>
[2024-11-06T09:05:30.303+0000] {logging_mixin.py:190} INFO - Failure caused by Cannot save file into a non-existent directory: '/Users/sushrinadhakal/***_stock/data'
[2024-11-06T09:05:30.303+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=stock_etl_dag, task_id=extract_data, run_id=manual__2024-11-06T09:05:23.848721+00:00, execution_date=20241106T090523, start_date=20241106T090527, end_date=20241106T090530
[2024-11-06T09:05:30.338+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-06T09:05:30.339+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 35 for task extract_data (Cannot save file into a non-existent directory: '/Users/sushrinadhakal/***_stock/data'; 979)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/stock_dag.py", line 16, in extract_stock_data
    data.to_csv('/Users/sushrinadhakal/airflow_stock/data/raw_data.csv')
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 3902, in to_csv
    return DataFrameRenderer(formatter).to_csv(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/format.py", line 1152, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/csvs.py", line 247, in save
    with get_handle(
         ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 739, in get_handle
    check_parent_directory(str(handle))
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 604, in check_parent_directory
    raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
OSError: Cannot save file into a non-existent directory: '/Users/sushrinadhakal/***_stock/data'
[2024-11-06T09:05:30.392+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-06T09:05:30.516+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-06T09:05:30.521+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
